#------swagger配置------
project:
  name: generate-interface-document
  version: 1.0.0
swagger:
  enabled: true
#  pathMapping: http://localhost:8080

#------spring配置------
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

  #------redis配置------
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #    password: 123456 #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  profiles:
    active: dev

#doc文档配置
doc:
  #xml生成的输出目录
  xmlPath: xml
  #word生成的输出目录
  outputDir: outFile
  # 模板文件存放的目录
  template: template
  #解压文件路径
  upZip: unZip
  zip: zip
  #加密密钥
  secret: asgfvwsesagfvqwdf